name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  schedule:
    - cron: '41 2 * * 6'
  workflow_dispatch:

jobs:
  test:
    name: Test ${{ matrix.arch }}
    runs-on: ${{ matrix.runs-on }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: 'x64'
            runs-on: windows-latest
          - arch: 'x86'
            runs-on: windows-latest
          - arch: 'arm64'
            runs-on: windows-11-arm

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up MSVC
        uses: h20y6m/actions-setup-msvc-env@v2
        with:
            arch: ${{ matrix.arch }}

      - name: Build test binary
        working-directory: tests
        run: cl.exe /MD /EHsc main.cpp

      - name: Copy VC++ runtime DLLs
        uses: ./
        with:
            bindir: tests

      - name: Check the copied DLLs
        working-directory: tests
        shell: pwsh
        run: |
          $dlls = Get-ChildItem -Filter "*.dll"
          if (-not $dlls) {
            throw "No DLLs were found."
          }
          else {
            $dlls
          }
